### ISSUE TITLE
关于更新功能的一点想法

### ISSUE THREAD

**Issue by overflow65537** [SweetSmellFox/MFAWPF#18]
用使用者的install文件来生成一个update补丁包,其中包含了interface.json和resource文件夹,在上传到发行版
优点是只需要下载补丁包就可以进行热更新.并且补丁包体积很小,在网络不稳定的情况下成功率会更高
缺点就是必须绑定这个install了

```
  update:
    needs: meta
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: update
        shell: bash
        run: |
          mkdir -p ./update
          rsync -av --exclude='MaaCommonAssets' ./assets/ ./update/


      - uses: actions/upload-artifact@v4
        with:
          name: update
          path: "update"
      

```
